### ISSUE TITLE
Connection Timed out error while connecting devarchy.com

### ISSUE THREAD

**Issue by shihokambara** [brillout/awesome-react-components#123]
when I tried to access `devarchy.com/react`, it returns Error 522(Connection timed out).
<img width="927" alt="Screen Shot 2019-08-04 at 18 36 15" src="https://user-images.githubusercontent.com/11058278/62422046-31294680-b6e7-11e9-98c0-ce0cab9b124d.png">

**Comment by bluepeter** [comment]
Yep... @brillout if you get a chance, can you remove the URL from this repo as it doesn't work?
