### ISSUE TITLE
Consider linking each Material-UI components? 

### ISSUE THREAD

**Issue by oliviertassinari** [brillout/awesome-react-components#139]
Hi, thank you for building this list, I think that it's very useful for the community.

I have one concern regarding Material-UI. (disclaimer, I work on the project). We have been working for the last 6 months, and continue to do so for the next year or two on transitioning people perception on the project. Material-UI is commonly interpreted as Material Design, but we believe it can be more than that: Material to build UI. We want to make it an one stop component store. Our roadmap is composed of 1. adding more components, 2. make theme more customizable, e.g. bootstrap theme, 3. make them lighter.

In this direction, I was wondering if you would consider linking each of our components in the corresponding categories? I have noticed that most of the ant design components are already linked (`rc-`). Now, you might be wondering. Wouldn't Material-UI components be bloated (by the way the link seems to be blank)? I can ensure you that we are working hard on making sure they are not. For instance, you can compare our Modal component with react-modal bundle size https://twitter.com/olivtassinari/status/1173695634018361349 vs https://bundlephobia.com/result?p=react-modal@3.10.1 or the cost of our slider 
https://material-ui.com/components/slider/ vs rc-slider https://bundlephobia.com/result?p=rc-slider@8.7.1

Thanks for the consideration.

**Comment by bluepeter** [comment]
Hi @oliviertassinari... I love Material-UI and use it everyday! (I am a small backer of your project, too.) How about providing a second level of bullet-points below the Material UI entry w/ direct links to key components? I'd like to keep the links to the same project centralized. Happy to review PRs here (including removing broken links or other entries that violate this approach)...

**Comment by oliviertassinari** [comment]
@bluepeter Thank you for the contribution on Patreon, it means a lot to me!

> How about providing a second level of bullet-points below the Material UI entry w/ direct links to key components?

I would help :). Happy to raise a PR with the components that have the most interest **outside** a Material Design point of view.

> I'd like to keep the links to the same project centralized.

Ok, I respect this. Does it mean the 7 ant design links (rc-calendar, rc-slider, rc-menu, rc-tooltip, rc-animate, rc-progress, ant-design) should be centralized under one? Would it be more compelling if Material-UI had different packages, documentation pages for the unstyled components?

**Comment by bluepeter** [comment]
@oliviertassinari glad to contribute! MUI has been a big part of our projects. (P.S., I am contributing via [Open Collective](https://opencollective.com/peter-bray), but I may swap to Patreon... didn't realize you had one... maybe OC uses Patreon on the back-end, dunno.)

PR would be great... *including* re-org of the ant links. (`ant` indeed should be centrally organized.) Separate listings for atypical material components sounds like a good approach.

As for MUI and splitting it into different packages, that's up to you. If you go that route, then feel free to list each separately under different headers here. But to the extent that each component is "mostly" part of the larger MUI, then my preference is to bullet them under MUI. The rationale behind this is that you guys have dozens of components: to list each separately may reduce the "awesomeness" of the list.
