### ISSUE TITLE
awesome badge 

### ISSUE THREAD

**Issue by venky18** [brillout/awesome-react-components#14]
should add an [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome) badge and submit the list to [awesome](https://github.com/sindresorhus/awesome)

**Comment by brillout** [comment]
The catalog is not part of the awesome list.

There already was a PR, see https://github.com/sindresorhus/awesome/pull/698.

As for the merge mentioned in the PR; https://github.com/enaqx/awesome-react/issues/503.

I'm currently using devarchy to manage entry additions. I don't know if @enaqx and @brownfield are up for that. I don't want to push changes to the repository without their approval.

**Comment by enaqx** [comment]
@brillout Thanks for efforts. Components section in awesome-react is pretty outdated and need major review. If you will make it with merging your list and make PR for our review it would be awesome. 👍

**Comment by venky18** [comment]
got it. closing the issue.
