### ISSUE TITLE
React universal hooks

### ISSUE THREAD

**Issue by salvoravida** [brillout/awesome-react-components#154]
Hi,
is there a category for this?

https://github.com/salvoravida/react-universal-hooks
React Universal Hooks : just use****** everywhere. Support React >= 16.8.0

Why Universal Hooks?
use a customHook in your Component/Functional, without refactor.
useMemo & useCallback make PureComponents 100% pure! (max performance!)

**Comment by bluepeter** [comment]
You are welcome to propose a new category in a PR if we don't have one which can be used...
