### ISSUE TITLE
react-json-viewer

### ISSUE THREAD

**Issue by nsisodiya** [brillout/awesome-react-components#16]
Please add - 
https://github.com/nsisodiya/react-json-viewer
this is one of the most useful React component I ever created !!

**Comment by brillout** [comment]
> To add a component / library, add an entry at [devarchy.com/react-components](http://devarchy.com/react-components). 

is there a reason you didn't do so?

**Comment by nsisodiya** [comment]
Sorry, I do not know about this facility - 
Doing it now !!
Thanks
