### ISSUE TITLE
Need to sort the Creator Sign Up based on the API order

### ISSUE THREAD

**Issue by mongeslani** [brillout/awesome-react-components#27]
https://dev.90seconds.com/become-a-creator (login required)

Currently sorted by letter:

![screen shot 2016-11-15 at 2 26 02 pm](https://cloud.githubusercontent.com/assets/101984/20295377/8d5d6154-ab3f-11e6-9dc4-de118093dec8.png)

Need to fix the layout too:

![screen shot 2016-11-15 at 2 26 08 pm](https://cloud.githubusercontent.com/assets/101984/20295380/94ab7c16-ab3f-11e6-9104-f6f6658da865.png)

**Comment by RangerMauve** [comment]
This looks like its in the wrong repo.
