### ISSUE TITLE
Deprecated Server Communication Components

### ISSUE THREAD

**Issue by jakeanq** [brillout/awesome-react-components#289]
https://github.com/apollographql/react-apollo is now provided by https://github.com/apollographql/apollo-client (already listed) according to the Project's readme.

https://github.com/RickWong/react-transmit is also archived and does not appear to have been updated in 5 years.

Edit: https://github.com/cerebral-legacy/cerebral-module-http also appears to be replaced by https://github.com/cerebral/cerebral according to the former's readme.

**Comment by bluepeter** [comment]
Feel free to PR.

**Comment by ARVINDTRONICS** [comment]
This is fixed. Good to be marked as resolved @bluepeter

**Comment by RockingSNP** [comment]
Good to go
