### ISSUE TITLE
Add React Semantic UI to UI Frameworks

### ISSUE THREAD

**Issue by raptoria** [brillout/awesome-react-components#29]
http://react.semantic-ui.com/introduction

https://github.com/Semantic-Org/Semantic-UI-React

**Comment by W7PEA** [comment]
FYI @raptoria   https://github.com/brillout/awesome-react-components/blob/master/contributing.md

You can submit new entries on a different site...

**Comment by raptoria** [comment]
cool. I added another one, Pivotal UI!

**Comment by brillout** [comment]
Thanks! @W7PEA @raptoria
