### ISSUE TITLE
[ Themes ] Category: React

### ISSUE THREAD

**Issue by 0wczar** [brillout/awesome-react-components#30]
Hi,

Maybe add categories „Themes”? 

Thanks,
Tomasz

**Comment by brillout** [comment]
which libraries would you put in it?

**Comment by 0wczar** [comment]
I do not know if we understand each other?

Example:
- http://rubix410.sketchpixy.com

**Comment by 0wczar** [comment]
@brillout good idea?

**Comment by brillout** [comment]
Is it open source? The catalog hosts only open source stuff

**Comment by 0wczar** [comment]
It is a charge ($20 + Lifetime support).

But people are also looking for such ready-made solutions.


dnia 16 grudnia 2016 o 14:22:33, brillout (notifications@github.com)
napisał:

Is it open source? The catalog hosts only open source stuff

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/brillout/awesome-react-components/issues/30#issuecomment-267592837>,
or mute the thread

**Comment by brillout** [comment]
Sorry only open source stuff

**Comment by brillout** [comment]
Not in this catalog.

But we could create a new catalog of such paid & non-open source frameworks.

**Comment by 0wczar** [comment]
It would be great.
