### ISSUE TITLE
Antd

### ISSUE THREAD

**Issue by xogeny** [brillout/awesome-react-components#31]
You don't mention ant design at all.  It is very nice: http://ant.design/

**Comment by brillout** [comment]
Hi @xogeny,

 - please read the contrib guideline and use devarchy to add a component
 - https://ant.design/docs/pattern/navigation is not translated in english. Most users here don't understand non-english docs

If you commit to sustainably translate all docs to english, than I'll add it to the catalog

**Comment by xogeny** [comment]
I'm not affiliated with the project and I certainly can't translate from Chinese to English.  But I was referring to the React component library (what I've been using).  [All the docs there](https://ant.design/docs/react/introduce) are in English?  Isn't that sufficient?

**Comment by chbdetta** [comment]
now that antd has english docs, you should consider adding it to the index.
https://ant.design/docs/react/introduce

**Comment by brillout** [comment]
There are still some pages that are missing an English translation but I guess it's ok.
Both `antd` and `antd-mobile` are now part of the catalog. Thanks @xogeny @chbdetta
