### ISSUE TITLE
Add boilerplate for React, TypeScript, postCSS, CSS-Modules, Webpack 2 and Live Reloading

### ISSUE THREAD

**Issue by jquintozamora** [brillout/awesome-react-components#37]
Here the url: https://github.com/jquintozamora/react-typescript-webpack2-cssModules-postCSS

Note: I didn´t use devarchy because the project doesn´t have npm package

**Comment by brillout** [comment]
Hi @jquintozamora 

Thanks for opening the issue.

The boilerplate category is getting quite big. It would be nice if we can break it down into smaller categories. What do you think?

**Comment by brillout** [comment]
The boilerplate category is way too long. We need to break it down into small categories. I'll gladly add your boilerplate afterwards.
