### ISSUE TITLE
Remove "carte-blanche"

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [brillout/awesome-react-components#373]
Hi, I was checking this pkg out and found this written on it: `IMPORTANT: This project is unfinished and not maintained. Do not try to use it, it likely does not work anymore.`.

And latest commits were 3 on the README, 6, 7 years ago on the rest. So, safe to say, this project is abandoned. Should it be removed from the list?

Furthermore, what are the characteristics that a project has to have to qualify to be on this awesome list? Because I've seen a few that also seem to be abandoned...

**Comment by bluepeter** [comment]
Please definitely PR deletion of any you see that have not been updated for a while. We rely on users to propose deletions when something is no longer awesome.

**Comment by Gabriel-Alves-Cunha** [comment]
Alright, will open a PR.
