### ISSUE TITLE
[Suggestion] Add a 'back to top' button in every section.

### ISSUE THREAD

**Issue by samyabrata-maji** [brillout/awesome-react-components#380]
In the README.md file, add a 'back to top' button after every section. Makes navigation much smoother.

**Comment by bluepeter** [comment]
Good idea, but I am not sure if that is possible in Markdown on GH?

**Comment by samyabrata-maji** [comment]
It think it is possible. I'll you know if it is possible.

**Comment by samyabrata-maji** [comment]
Yeah I can do it. Assign me

**Comment by samyabrata-maji** [comment]
Added a `back to top` button after every H2 ( ' ## ' ) element.
- Navigates back to `Table of Contents`
- See changes: [click here](https://github.com/samyabrata-maji/awesome-react-components/commit/4bce725329da46c6a7ca73c7ba30d007300cb3c1)

Should I send a PR or do you want me to add `back to top` buttons after ever sub menu H3  ( ' ### ' ) element?

**Comment by bluepeter** [comment]
I'd recommend PR'ing what you have now.

**Comment by bluepeter** [comment]
Fixed in above PR. Thank you @samyabrata-maji
