### ISSUE TITLE
Are pull requests appreciated to this repository?

### ISSUE THREAD

**Issue by vsnthdev** [brillout/awesome-react-components#389]
Firstly, I am glad I stumbled upon such a great collection of React components! ✨

I'd love to **send a PR to remove a few archived, outdated and deleted repositories** from the list.

Is such a PR appreciated? Below are a few projects I've found which are either deleted, archived or not being updated from a long time 👇

### Proposed removals

1. [react-block-ui](https://github.com/availity/react-block-ui) — Archived on Feb 21, 2023.
2. [velocity-react](https://github.com/google-fabric/velocity-react) — Archived on Nov 3, 2021.
3. [react-aim](https://github.com/gabrielbull/react-aim) — Archived on Feb 12, 2022.
4. [react-find](https://github.com/geobde/react-find)  — Deleted repository.

**Comment by bluepeter** [comment]
Yeah definitely. Go for it.

**Comment by vsnthdev** [comment]
Thank you! I'll send a PR in sometime 🚀
