### ISSUE TITLE
Add PrimeReact

### ISSUE THREAD

**Issue by cagataycivici** [brillout/awesome-react-components#46]
There is also PrimeReact, a young open source library from the guys who created popular PrimeFaces (jsf) and PrimeNG (angular) libraries. http://www.primefaces.org/primereact/

**Comment by brillout** [comment]
I added it to https://devarchy.com/react/need/component-set

@cagataycivici @deadcoder0904 Why did you guys not use devarchy to add it? Thanks for the PR though
