### ISSUE TITLE
Count of stars is not updated

### ISSUE THREAD

**Issue by kirill3333** [brillout/awesome-react-components#55]
Hi I've added my component https://github.com/kirill3333/react-avatar
When I aded it has 2 stars. Now It has 13 stars.
However on the website it still 2 stars. It also true for another components

<img width="1392" alt="screen shot 2017-10-25 at 17 21 44" src="https://user-images.githubusercontent.com/1804678/32003967-5df2e83e-b9a9-11e7-8af8-5c0c8848c8bf.png">

**Comment by paulmelnikow** [comment]
Can confirm. At [this link](https://devarchy.com/react/need/markdown-editor) react-codemirror is showing 610 instead of 810 stars.

**Comment by brillout** [comment]
I'm aware of this. I'll keep you guys in touch. Thanks for letting me know!

**Comment by bluepeter** [comment]
Closing out-of-date issue.
