### ISSUE TITLE
Add lingui js to i18n

### ISSUE THREAD

**Issue by HariSeldon23** [brillout/awesome-react-components#58]
It's a great React tool for internationalization and should be included in this list.

**Comment by tricoder42** [comment]
I've already add it https://devarchy.com/react/topic/i18n, now waiting for upvotes. Thanks @HariSeldon23 and @brillout

**Comment by tricoder42** [comment]
@brillout How does the scoring actually works? My lib has 3 upvotes and still awaiting... other accepted libs usually have 2 or less upvotes.

**Comment by HariSeldon23** [comment]
Just upvoted now :)

**Comment by bluepeter** [comment]
Closing out-of-date issue.
