### ISSUE TITLE
Should deprecated components be removed?

### ISSUE THREAD

**Issue by cjbassi** [brillout/awesome-react-components#60]
It looks like [react-async](https://github.com/andreypopp/react-async) is deprecated and hasn't been updated in a while either. I think it would make sense to remove it from the list. Any reason not to?

**Comment by betsydupuis** [comment]
[fixed-data-table](https://github.com/facebookarchive/fixed-data-table) is also no longer maintained.

**Comment by bluepeter** [comment]
Thanks, please PR any derelict components and we will remove.
