### ISSUE TITLE
Should add downshift (autocomplete select component)

### ISSUE THREAD

**Issue by drmikeh** [brillout/awesome-react-components#67]
I recommend adding downshift, an autocomplete select / dropdown component written by Kent C. Dodds for PayPal). See https://github.com/paypal/downshift and the blog post is at https://blog.kentcdodds.com/introducing-downshift-for-react-b1de3fca0817.

**Comment by brillout** [comment]
Is there a reason you didn't use https://devarchy.com/react to add it?

**Comment by bluepeter** [comment]
@drmikeh please PR these components in this repo and we will review.
