### ISSUE TITLE
React component for reading comics

### ISSUE THREAD

**Issue by ridhwaans** [brillout/awesome-react-components#74]
I'm looking for a react component that reads CBR and CBZ file formats (comics). I can't find one or I can build it myself

**Comment by streamich** [comment]
If you find one or create one, please let us know!

**Comment by ItamarShDev** [comment]
A good start point ? https://www.raymondcamden.com/2012/05/29/Building-an-HTML5-Comic-Book-Reader

**Comment by bluepeter** [comment]
Unrelated to this list. Closing. (Please PR if you find one, of course.)
