### ISSUE TITLE
can't login on devarchy

### ISSUE THREAD

**Issue by stalniy** [brillout/awesome-react-components#76]
**Steps**:
1. Click on login with github button
2. it redirects to `http://localhost:8081/auth/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=cbcoxlgOqE2TQ2nZ5bDpvM`

**Comment by brillout** [comment]
Should be working again.

Re-open if you still encounter problems.

Thanks.
