### ISSUE TITLE
Authorization on website is broken

### ISSUE THREAD

**Issue by asmyshlyaev177** [brillout/awesome-react-components#79]
When click on "log in" button page redirect to http://localhost:8081/auth/github
Must be https://devarchy.com/auth/github

**Comment by bluepeter** [comment]
To suggest changes, please PR to this repo and we will review.

**Comment by asmyshlyaev177** [comment]
It's about devarchy website, not about list or resources.

**Comment by bluepeter** [comment]
Yep, I know. The list of resources in this repo is now managed exclusively via PRs for now.
