### ISSUE TITLE
New Components

### ISSUE THREAD

**Issue by JosephSmith127** [brillout/awesome-react-components#86]
I'd like to add the following:

https://github.com/JosephSmith127/react-avatar-generator
https://github.com/JosephSmith127/react-color-scroll

probably both under miscellaneous though https://devarchy.com/react is not working. Can you add them in?

<img width="1007" alt="screenshot 2019-01-10 at 05 31 48" src="https://user-images.githubusercontent.com/4484836/50948107-09e40100-1499-11e9-82bf-5dea702209ff.png">

**Comment by sudomann** [comment]
I see there have been no commits to this repo in 2 years now. Is it pending archiving or deprecation? Seemed pretty active up till 2017.

**Comment by bluepeter** [comment]
Please PR and we will review.
